/*
 * creeper.c
 *
 *  Created on: February 12, 2016
 *  Updated on: February 12, 2016
 *      Author: Logan
 */

#include <stdio.h>
#include "Colours.h"
#include "graphics.h"

//colours used for heart
#define HEART_COLOUR_1 BLACK
#define HEART_COLOUR_2 PINK
#define HEART_COLOUR_3 LIGHT_CORAL
#define HEART_COLOUR_4 RED
#define HEART_COLOUR_5 FIREBRICK
#define HEART_COLOUR_6 GRAY
#define BLANK -1

//pixel width of heart bitmap
#define HEART_PIXEL_WIDTH 13
#define HEART_PIXEL_HEIGHT	11


/* Static Functions */
static void heart_generator(int x, int y, int pixelSize);
static void heart_empty_generator(int x, int y, int pixelSize);


void heart_draw(int x, int y, int width) {
	int pixelSize = width / HEART_PIXEL_WIDTH;

	heart_generator(x, y, pixelSize);
}

void heart_draw_empty(int x, int y, int width) {
	int pixelSize = width / HEART_PIXEL_WIDTH;

	heart_empty_generator(x, y, pixelSize);
}

/*
 * generates a heart
 * x - top left x coordinate
 * y - top left y coordinate
 * pixelSize - width and length of each pixel box
 */
static void heart_generator(int x, int y, int pixelSize) {
	int i, j;
	int tempX = x;

	int fullHeartColours[HEART_PIXEL_HEIGHT][HEART_PIXEL_WIDTH] = {
								{BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_1, HEART_COLOUR_1, BLANK, BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_1, HEART_COLOUR_1, BLANK, BLANK}, //row 1
								{BLANK, HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_1, BLANK, HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_1, BLANK}, //row 2
								{HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_2, HEART_COLOUR_3, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_1}, //row 3
								{HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_3, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_1}, //row 4
								{HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_5, HEART_COLOUR_1}, //row 5
								{BLANK, HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_5, HEART_COLOUR_1, BLANK}, //row 6
								{BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_5, HEART_COLOUR_1, BLANK, BLANK}, //row 7
								{BLANK, BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_5, HEART_COLOUR_1, BLANK, BLANK, BLANK}, //row 8
								{BLANK, BLANK, BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_4, HEART_COLOUR_5, HEART_COLOUR_1, BLANK, BLANK, BLANK, BLANK}, //row 9
								{BLANK, BLANK, BLANK, BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_4, HEART_COLOUR_1, BLANK, BLANK, BLANK, BLANK, BLANK}, //row 10
								{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, HEART_COLOUR_1, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK}}; //row 11

	//implements graphics based on colors from color matrix heartColours
	for (i = 0; i < HEART_PIXEL_HEIGHT; i++) {
		for (j = 0; j < HEART_PIXEL_WIDTH; j++) {
			//BLANK
			if(fullHeartColours[i][j] != BLANK) {
				graphics_draw_rectangle_filled(x, y, pixelSize, pixelSize, fullHeartColours[i][j]);
			}
			x += pixelSize;
		}
		x = tempX;
		y += pixelSize;
	}
}

void heart_erase(int x, int y, int width) {
	int pixelSize = width / HEART_PIXEL_WIDTH;
	graphics_draw_rectangle_filled(x, y, pixelSize * HEART_PIXEL_WIDTH,
			pixelSize * HEART_PIXEL_HEIGHT, GRAPHICS_BACKGROUND_COLOUR);
}

static void heart_empty_generator(int x, int y, int pixelSize) {
	int i, j;
	int tempX = x;

	int emptyHeartColours[HEART_PIXEL_HEIGHT][HEART_PIXEL_WIDTH] = {
								{BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_1, HEART_COLOUR_1, BLANK, BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_1, HEART_COLOUR_1, BLANK, BLANK}, //row 1
								{BLANK, HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_1, BLANK, HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_1, BLANK}, //row 2
								{HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_1}, //row 3
								{HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_1}, //row 4
								{HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_1}, //row 5
								{BLANK, HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_1, BLANK}, //row 6
								{BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_1, BLANK, BLANK}, //row 7
								{BLANK, BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_1, BLANK, BLANK, BLANK}, //row 8
								{BLANK, BLANK, BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_6, HEART_COLOUR_1, BLANK, BLANK, BLANK, BLANK}, //row 9
								{BLANK, BLANK, BLANK, BLANK, BLANK, HEART_COLOUR_1, HEART_COLOUR_6, HEART_COLOUR_1, BLANK, BLANK, BLANK, BLANK, BLANK}, //row 10
								{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, HEART_COLOUR_1, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK}}; //row 11

	//implements graphics based on colors from color matrix heartColours
	for (i = 0; i < HEART_PIXEL_HEIGHT; i++) {
		for (j = 0; j < HEART_PIXEL_WIDTH; j++) {
			//BLANK
			if(emptyHeartColours[i][j] != BLANK) {
				graphics_draw_rectangle_filled(x, y, pixelSize, pixelSize, emptyHeartColours[i][j]);
			}
			x += pixelSize;
		}
		x = tempX;
		y += pixelSize;
	}
}
